# -----------------------------------------------------
# |         Alps-Hub Plugin - by Alps BTE
# -----------------------------------------------------
# | [Github Repo] https://github.com/AlpsBTE/Hub
# -----------------------------------------------------

# Chat Formatting
chat-format:
  info-prefix: ''
  alert-prefix: ''
  arrow: '<dark_gray> » </dark_gray>'

# Spawn
spawn:
  world: 'Hub'
  x: 550.5
  y: 53
  z: 576.5
  pitch: -1.2
  yaw: 135.3

# Servers
servers:
  plot:
    plot-name: 'ALPS-1'
    plot-IP: localhost
    plot-port: 00000
  terra:
    terra-name: 'ALPS-2'
    terra-IP: localhost
    terra-port: 00000

# Enable/Disable Commands
cmd-hub: false
cmd-spawn: true
cmd-switch: true
cmd-tpp: true
cmd-speed: true
cmd-ptime: true
cmd-pweather: true

# Others
right-click-iron-trap-doors: true
teleport-player-to-spawn-on-join: false


# NOTE: Do not change
config-version: 1.1