# -----------------------------------------------------
# |         Alps-Hub Plugin - by Alps BTE
# -----------------------------------------------------
# | [Github Repo] https://github.com/AlpsBTE/Hub
# -----------------------------------------------------

# Chat Formatting
chat-format:
  info-prefix: ' <dark_gray> » </dark_gray>'
  alert-prefix: ' <dark_gray> » </dark_gray>'

# Spawn Location
spawn:
  world: 'Hub'
  x: 550.5
  y: 53
  z: 576.5
  pitch: -1.2
  yaw: 135.3

# Servers
servers:
  - name: 'ALPS-1'
    address: 'localhost'
    port: 0000
  - name: 'ALPS-2'
    address: 'localhost'
    port: 0000

# Enable/Disable Commands
commands:
  hub: true
  spawn: true
  switch: true
  tpp: true
  speed: true
  ptime: true
  pweather: true

# Enable/Disable join and leave messages
send-join-leave-message: false

# Teleport the player to the configured spawn location on join
teleport-player-to-spawn-on-join: false

# Cosmetics
cosmetics:
  enabled: true
  hats:
    - name: 'Hard Hat'
      permission: ''
      material: 'PAPER'
      model-data: ''

# NOTE: Do not change
version: 1